name: Some Workflow
on:
  workflow_dispatch:

jobs:  
  build:
    environment:
      staging
    env:
      database-name: ${{ env.staging }}
      project-name: ${{ github.ref_name }}
    outputs:
      someValue: ${{ steps.upload-failed-report.outputs.report-message }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          key: dependencies-key-${{ hashFiles() }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm build
      - name: Upload Artifact
        id: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          path: build/
          name: build-artifact
      - name: Upload Failed Report
        if: failure() && steps.upload-artifact.outcome == "failure"
        id: upload-failed-report
        run: echo 'report-message="something went wrong in the project" ${{ env.project-name }}' >> $GITHUB_OUTPUT
        
          
